sonar.projectKey=NHSDigital_gp2gp-enhanced-mi-infrastructure
sonar.organization=nhsdigital

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=gp2gp-enhanced-mi-infrastructure
sonar.projectVersion=1.0

sonar.python.version=3.13

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.
sonar.sources=lambda/, stacks/

sonar.python.coverage.reportPaths=services/**/coverage.xml

sonar.exclusions=stacks/**,**/venv/**,.github/**,**/*.yml,**/*.yaml,**/*.md,**/__init__.py
