sonar.projectKey=NHSDigital_gp2gp-enhanced-mi-infrastructure
sonar.organization=nhsdigital

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=gp2gp-enhanced-mi-infrastructure
sonar.projectVersion=1.0

sonar.python.version=3.13
sonar.sourceEncoding=UTF-8

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.

sonar.sources=.
#sonar.inclusions=lambdas/**/*.py, lambdas/*.py, stacks/**/*.tf
#sonar.inclusions=lambdas/**
sonar.tests=lambdas/tests
sonar.test.inclusions=lambdas/tests/**/test_*.py

sonar.python.coverage.reportPaths=lambdas/coverage.xml
sonar.exclusions=**/venv/**, .github/**, **/*.yml, **/*.yaml, **/*.md, lambdas/build/**
